#Ansible playbook utilising Ansible_pyats role to take a comparison snapshot of routing table
---
- name: Snapshot output test
  hosts: SB-SW-01
  gather_facts: no
  connection: network_cli
  roles:
    - ansible-pyats
  tasks:
    - include_role:
        name: ansible-pyats
        tasks_from: compare_command
      vars:
        command: show ip route
        file: "{{ inventory_hostname }}_routes.json"