
---
- name: Structured output test
  hosts: SB-SW-01
  gather_facts: no
  connection: network_cli
  roles:
    - ansible-pyats
  tasks:
    - pyats_parse_command:
        command: show ip route
      register: output

    - debug:
        var: output.structured