---
# Ansible playbook using ansible.bulitin.setup and napalm to restore configuration
# From a directory (date stamped) when there is a difference found in the config
# Note: For IOS devices with banners you must use converter.py to change the ^C character to etx
# otherwise you will get an error from the playbook. 
# Also IOS devices must be running scp server and have the archive path set (i.e. path flash:archive)

- name: "Play1: Collect the date / time from local host"
  hosts: localhost

  tasks:
    - name: "Task 1 of Play 1: Collect facts about local host"
      ansible.builtin.setup:
        filter:
          - "ansible_date_time"
      
    - name: "Task 2 of Play 1: Recording Variable called DATE"
      set_fact:
        DATE: "{{ ansible_date_time.date }}"

    - name: "Task 3 of Play 1: Creating diff directory"
      hosts: Arista, Canada
      connection: network_cli

      tasks:
        - name: "Create a Diff directory"
          file: 
            path: "diffs/{{ hostvars.localhost.DATE }}/{{ inventory_hostname }}"
            state: directory
          run_once: false

    - name: "Use Napalm to Restore Backup configuration if there is any differences"
      napalm_install_config:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        config_file: "Backups/2022-05-08/running-configs/{{ inventory_hostname }}-running-config.txt"
        commit_changes: true
        replace_config: true
        get_diffs: true
        diff_file: diffs/{{ hostvars.localhost.DATE }}/{{ inventory_hostname }}/{{ inventory_hostname }}-diffs.txt
        optional_args:
          global_delay_factor: 2
      register: result

    - name: "Print Result"
      debug:
        msg: "{{ result }}"
...
