---
- name: Hardening the Configuration of the Switches as per Best Practice
  hosts: North_Switches, South_Switches
  gather_facts: no

  vars:
    ansible_network_os: ios

  tasks:
  - name: no service pad
    ios_config:
      lines:
        - no service pad

  - name: IP SSH VERSION 2 
    ios_config:
      lines:
        - ip ssh version 2

  - name: NO IP DOMAIN-LOOKUP
    ios_config:
      lines:
        - no ip domain-lookup

  - name: DISABLE HTTP MANAGMENT 
    ios_config:
      lines:
        - no ip http server
       
  - name: DISABLE IP FINGER 
    ios_config:
      lines:
        - no ip finger 

  - name: DISABLE IP BOOT SERVER 
    ios_config:
      lines:
        - no ip bootp server       

  - name: SERVICE TCP-KEEPALIVES-IN
    ios_config:
      lines:
        - service tcp-keepalives-in  
 
  - name: SERVICE TCP-KEEPALIVES-OUT
    ios_config:
      lines:
        - service tcp-keepalives-out

  - name: TRANSPORT INPUT SSH 
    ios_config:
      parents: line vty 0 4
      lines:        
        - transport input ssh

  - name: LOGGING BUFFERED 15000 
    ios_config:
      lines:
        - logging buffered 15000
 
  - name: Saving the configuration 
    ios_config:
      lines:
        - do wr mem    
...
