---
# Playbook to configure Nexus Switch - single command

- hosts: nxsw01

  tasks: 
    - name: Configure a single command on Nexus 
      nxos_config: 
        lines: ntp server 9.9.9.9 use-vrf default
        save_when: modified 

...
