---
- name: "Playbook to test Napalm-Ansible"
  hosts: Canada, vEOS
  connection: network_cli

  tasks:
    - name: "Retrieve device facts from via NAPALM"
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        filter: ["facts"]
      register: result

    - name: "Print Result"
      debug:
        msg: "{{ result.ansible_facts.napalm_facts }}"
# filtering the results down to specific information
...
