---
- name: "Play1: Collect the date / time from local host"
  hosts: localhost

  tasks:
    - name: "collect date / time information"
      ansible.builtin.setup:
        filter:
          - "ansible_date_time"

    - name: "Task 2 of Play 1: Recording Variable"
      set_fact:
        DATE: "{{ ansible_date_time.date }}"

- name: "Play 2: Arista devices"
  hosts: EOS-1
  connection: network_cli

  tasks:
    - name: "Create a Diff directory"
      file: 
        path: "diffs/{{ hostvars.localhost.DATE }}/{{ inventory_hostname }}"
        state: directory
      run_once: false
    
    - name: "Use Napalm to Restore Backup configuration"
      napalm_install_config:
        hostname: " {{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        config_file: "{{ inventory_hostname }}-running-config.txt"
        commit_changes: true
        replace_config: true
        get_diffs: true
        diff_file: diffs/{{ hostvars.localhost.DATE }}/{{ inventory_hostname }}/{{ inventory_hostname }}-diffs.txt
        optional_args:
          global_delay_factor: 2
      register: result

    - name: "Print Result"
      debug:
        msg: "{{ result }}"


