---
- name: "Playbook to test Napalm-Ansible"
  hosts: Canada, vEOS
  connection: network_cli

  tasks:
    - name: "Retrieve device facts from via NAPALM"
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        filter: ["mac_address_table"]
      register: result
# Using filter to filter on a specific Napalm getter

    - name: "Print Result"
      debug:
        msg: "{{ result.ansible_facts.napalm_mac_address_table }}"
# filtering the results down to specific information
...
