## Ansible snapshot playbook, takes a snapshot of 
## the running configs on the hosts and saves them
## to directory so you can run a debugger playbook
## to check for changes should there be issues

---
- name: "Initialising Ansible Network Snapshot!..."  
  hosts: localhost

  tasks:
    - name: "Job 1 of PLAY 1: Enumerate Local Time & Date..."
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"

    - name: "Job 2 of PLAY 1: Record Information as variable: TimeDate"
      set_fact:
        TD: "{{ ansible_date_time.date }}"

    - name: "Job 3 of PLAY1: Creating Calendar Subfolders..."
      file:
        path: ~/Calendar/{{hostvars.localhost.TD}}
        state: directory
      run_once: true


- name: "PLAY 2: Capture network Snapshot of current configurations"
  hosts: "vIOS"
  connection: network_cli
  tasks:
    - name: "Job 1 of PLAY 2: Retrieve Runnings Configs."
      ios_command:
        commands: 
          - show run 
      register: response

    - name: "Job 2 of PLAY 2: Create Snapshot Subfolder..."
      file:
        path: "~/Calendar/{{hostvars.localhost.TD}}/snapshots"
        state: directory
      run_once: true

    - name: "Job 3 of PLAY 2: uploading data to the target subfolder..."
      copy: 
        content: "{{ response.stdout[0] }}\n"
        dest: "~/Calendar/{{hostvars.localhost.TD}}/snapshots/{{ inventory_hostname }}-running-config.txt"
...