# Playbook to push config file using commands listed in push.txt

- hosts: all
  connection: network-cli
  gather_facts: false

  tasks:
  - name: Push config file 
    ios_config:
      src: "./configs/push.txt"

  - name: Save config when modified
    ios_config:
      save_when: modified

...
