---
- name: "Playbook to test Genie Collection"
  hosts: NN-SW-01
  connection: network_cli
  gather_facts: false

  tasks:
  - name: "TASK1 - send a show command"
    cisco.ios.ios_command:
      commands: 
      - show version
    register: show_version_output