---
# Playbook using RESTCONF to configure an IOSXE device. It pulls the
# ospf and acl data from the host_vars file for the host

- name: "Configuring IOSXE Devices via RESTCONF"
  hosts: CSR-1
  connection: local
  tasks:

    - name: "Task 1 - Configure OSPF"
      uri:
        url: "https://{{ ansible_host }}/restconf/data/native/router"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: PUT
        headers:
          Accept:
            application/yang-data+json,
            application/yang-data.errors+json
          Content-Type: 'application/yang-data+json'
        body_format: json 
        body: "{{ ospf }}"
        validate_certs: false
        status_code:
          - 400

    - name: "Task 2 - Configure an ACL"
      uri:
        url: "https://{{ ansible_host }}/restconf/data/native/ip/access-list"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: PUT
        headers:
          Accept:
            application/yang-data+json,
            application/yang-data.errors+json
          Content-Type: 'application/yang-data+json'
        body_format: json 
        body: "{{ acl_1 }}"
        validate_certs: false
        status_code:
          - 200
          - 204
...
