#Ansible Playbook to add priviledge users to devices
---
- name: add users
  hosts: NN-SW-01
  gather_facts: no

#Add the new user names in the vars section:
  vars:
     names:
       - user1
       - user2

  tasks:
  - name: add users
    cisco.ios.ios_user:
      name: "{{ item }}"
      state: present
      privilege: 15
      password_type: secret
      update_password: on_create
    no_log: true
    with_items: "{{ names }}"
    notify: save
#The above section is going to take the names listed in vars and add them with priv 15 access
  handlers:
    - name: save
      ios_config:
        save_when: modified
