# Playbook using ansible facts module to display serial number of the host
---
- name: Use Ansible Facts to display host serial number
  hosts: CSR_hosts
  connection: network_cli

  tasks:
    - name: Gather switch facts
      cisco.ios.ios_facts:

    - name: Display Serial number
      ansible.builtin.debug:
        msg: "The Serial number is: {{ ansible_net_serialnum }}"
...
