# Ansible Playbook to show ip routing table summary on cisco device 
---

- name: Show summarised IP routing table
  hosts: SB-SW-01
  gather_facts: false
  connection: network_cli
  
  tasks:
  - name: Show IP routing table summary 
    cisco.ios.ios_command:
      commands:
      - command: "Show ip route summary"
    register: print_output
  - debug: var=print_output.stdout_lines
