# Ansible playbook to show ip route on cisco ios devices and print the output to screen
---

- name: Get IP routes
  hosts: Selby
  gather_facts: false
  connection: network_cli
  
  tasks:
    - name: show IP route on devices
      cisco.ios.ios_command:
        commands:
        - command: "Show ip route"
      register: print_output
    - debug: var=print_output.stdout_lines
...
