# Ansible Playbook to show cdp neighbors on cisco devices 
---

- name: Show CDP neighbors
  hosts: Core1
  gather_facts: false
  connection: network_cli
  
  tasks:
  - name: Show CDP neighbors
    cisco.ios.ios_command:
      commands:
      - command: "Show cdp neighbor"
    register: print_output
  - debug: var=print_output.stdout_lines
