# Ansible Playbook to add a new VRF to router
---
- name: Add VRF to ios Routers
  hosts: routers
  connection: network_cli
  gather_facts: false

  vars:
    thestate: merged
    vrf_name: sample_vrf
    vrf_description: added by Ansible
# Add the vrf names and decription above

  tasks:

    - name: Configure the vrf name for the vrf
      cisco.ios.ios_vrf:
        name: "{{ vrf_name }}"
        description: "{{ vrf_description }}"
        state: present
      when: thestate == "merged"

    - name: Remove the named vrf
      cisco.ios.ios_vrf:
        name: "{{ vrf_name }}"
        state: absent
      when: thestate == "deleted"
...
