# Playbook to add BGP configuration from Jinja 2 template
---
- name: Configure BGP from Jinja template
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Configuring BGP
      cisco.ios.ios_config:
        src: "BGP.j2"
        save_when: modified
      notify: bgp_handler
      register: bgp_result

  handlers:
    - name: Now checking if BGP config has been successfully changed
      listen: bgp_handler
      ansible.builtin.debug:
        msg: "CONFIG THAT HAS BEEN ADDED: {{ bgp_result.commands }}"
...
