# This playbook is for:
# Upgrading from Cisco IOS XE 3.xE to Cisco IOS XE Denali 16.1.1, 16.1.2, or 16.1.3 in Install Mode
# https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst3650/software/release/16-1/release_notes/ol-16-1-3650.html
---
- name: Upgrade a Cisco IOS Device
  hosts: switches
  tasks:
    - name: Gathering Facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Disable file task prompting
      cisco.ios.ios_config:
        lines:
          - file prompt quiet
      timeout: 60
      when: ansible_net_version != standard_version

    - name: Copying image from ftp server to device flash
      cisco.ios.ios_command:
        commands: "copy ftp://{{ username }}:{{ password }}@{{ ftp_server_ip }}/{{ ftp_server_path }}/{{ image }} flash:\n\n"
      timeout: 10800
      when: ansible_net_version != standard_version
      tags: copy

    - name: Get MD5 Hash from uploaded file
      cisco.ios.ios_command:
        commands: "verify /md5 {{ image }}"
      timeout: 3600
      when: ansible_net_version != standard_version
      register: md5_check_output
      tags: calc_hash

    - name: Set the facts
      ansible.builtin.set_fact:
        md5_calc_checksum: "{{ md5_check_output.stdout_lines[0][1] }}"
      when: ansible_net_version != standard_version
      tags: calc_hash

    - name: MD5 Checksum Output
      ansible.builtin.debug:
        var: md5_calc_checksum
      when: ansible_net_version != standard_version
      tags: calc_hash

    - name: Verify MD5 hash is correct
      ansible.builtin.debug:
        msg: Verify MD5 has is correct
      failed_when: image_md5 not in md5_calc_checksum
      when: ansible_net_version != standard_version
      tags: calc_hash

    - name: Clean up software
      cisco.ios.ios_command:
        commands:
          - command: 'software clean'
            prompt: '\[yes\/no\]:'
            answer: 'yes'
      timeout: 1800
      when: ansible_net_version != standard_version
      tags: clean

    - name: Install software to flash of switch(es)
      cisco.ios.ios_command:
        commands: "software install file flash:{{ image }} new force on-reboot"
      timeout: 1800
      when: ansible_net_version != standard_version
      tags: install_software

  handlers:
    - name: Save the config
      cisco.ios.ios_config:
        save_when: always
...
