# Ansible playbook to set some basic global settings to cisco IOS devices
---
- name: Globaly Configuration Playbook
  hosts: routers
  gather_facts: false
  connection: network_cli
  vars:
    ansible_command_timeout: 100

  tasks:
    - name: Router Global Settings
      cisco.ios.ios_config:
        lines:
          - security passwords min length 5
          - ip nameserver 8.8.4.4
          - no ip http server
          - ip http secure server
          - banner motd $***********WELCOME TO GH LAB**********$
      register: print_output

    - name: Output to screen
      ansible.builtin.debug:
        var: print_output.stdout_lines
...
