# Ansible playbook to add basic SNMP server configuraiton to cisco IOS devices
---
- name: Add basic SNMP Server config
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Add basic SNMP configuration
      cisco.ios.ios_config:
        lines:
          - service tcp-keepalives-in
          - service tcp-keepalives-out
          - snmp-server community labro
          - snmp-server enable traps
          - snmp-server host 80.80.80.1 version 2c labro
          - do wr mem
      register: print_output

    - name: Print the SNMP configuration output to screen
      ansible.builtin.debug:
        var: print_output
