# Ansible playbook to backup devices based on IOS version the backup files will be created in folders based on hostname
# and will be date stamped
---
- name: Backup running configuration based on IOS version
  hosts: Core1
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Get ansible date/time facts
      ansible.builtin.setup:
        filter: "ansible_date_time"
        gather_subset: "!all"

    - name: Store Date and time as fact
      ansible.builtin.set_fact:
        set_fact: "{{ ansible_date_time.date }}"

    - name: Backup running-config (IOSXE devices)
      cisco.ios.ios_config:
        backup: true
        backup_options:
          dir_path: "config_backups/IOSXE/{{ inventory_hostname }}"
          filename: "initial_running_config.{{ set_fact }}.cfg"
      when: ansible_network_os == "cisco.ios.ios"

    - name: Backup running-config (NXOS devices)
      cisco.nxos.nxos_config:
        backup: true
        backup_options:
          dir_path: "config_backups/NXOS/{{ inventory_hostname }}"
          filename: "initial_running_config.{{ set_fact }}.cfg"
      when: ansible_network_os == "cisco.nxos.nxos"
...
