# Playbook to Backup Cisco Config Files
---
- name: Backup Cisco Configs to a Directory
  hosts: Routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Gathering the subnet data
      ansible.builtin.setup:
        gather_subset: "!all"
        filter: "ansible_date_time"

    - name: Store date and time as a fact
      ansible.builtin.set_fact:
        set_fact: "{{ ansible_date_time.weekday }}"

    - name: Create the Directory
      ansible.builtin.file:
        path: "/etc/ansible/backups/{{ hostvars.localhost.set_fact }} -> /etc/ansible/backups/{{ hostvars.localhost.set_fact }}"
      run_once: true

    - name: Backup Running configs
      cisco.ios.ios_command:
        commands: show run
      register: config


    - name: Save output to ansible/backups folder and label files with hostname+date+time
      ansible.builtin.copy:
        content: "{{ config.stdout[0] }}"
        dest: "/etc/ansible/backups/{{ hostvars.localhost.set_fact }}/{{ inventory_hostname }}-{{ hostvars.localhost.set_fact }}-config.txt"
        mode: '644'

    - name: Saving the Configs
      cisco.ios.ios_config:
        save_when: modified
...
