## Ansible network debug playbook, to be used in conjunction
## with network snapshot to identify any changes to state of 
## hosts for fault finding purposes. Note: You must have ran
## network-snapshot.yml to be able to compare the outputs

---
- name: "Initialising Ansible"  
  hosts: localhost

  tasks:
    - name: "Job 1 of PLAY 1: Enumerate the Time/Date..."
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"

    - name: "Job 2 of PLAY 1: Recording Information as variable: TD"
      set_fact:
        TD: "{{ ansible_date_time.date }}"


- name: "PLAY 2: Capturing Current Running Configurations For Comparison..."
  hosts: vIOS
  connection: network_cli
  tasks:
    - name: "Job 1 of PLAY 2: Taking copy of current Runnings Configs."
      ios_command:
        commands: 
          - show run 
      register: response

    - name: "Job 2 of PLAY 2: Creating Comparison Subfolder..."
      file:
        path: "~/Calendar/{{hostvars.localhost.TD}}/comparison"
        state: directory
      run_once: true

    - name: "Job 3 of PLAY 2: Saving the output to target subfolder..."
      copy: 
        content: "{{ response.stdout[0] }}\n"
        dest: "~/Calendar/{{hostvars.localhost.TD}}/comparison/{{ inventory_hostname }}-running-config.txt"
...