# Ansible Playbook to show trunk interfaces on cisco switch(es) 
---

- name: Show trunk interfaces
  hosts: Core1
  gather_facts: false
  
  tasks:
  - name: Show interfaces configured as trunks  
    cisco.ios.ios_command:
      commands:
      - command: "Show int trunk"
    register: print_output
  - debug: var=print_output.stdout_lines
