# Ansible Playbook to show IP interface information on cisco devices 
---

- name: Show IP interface information
  hosts: North_Switches
  gather_facts: false
  
  tasks:
  - name: Show IP Interface Brief 
    cisco.ios.ios_command:
      commands:
      - command: "Show ip int bri"
    register: print_output
  - debug: var=print_output.stdout_lines
