# Ansible Playbook to show cpu usages in sorted format on cisco device 
---

- name: Show CPU and Memory usage
  hosts: NN-SW-01
  gather_facts: false
  
  tasks:
  - name: Show CPU and Memory usage by highest percentage order 
    cisco.ios.ios_command:
      commands:
      - command: "Show process cpu sorted"
      - command: "show process memory sorted"
    register: print_output
  - debug: var=print_output.stdout_lines
