# Ansible Playbook to show state of the ospf neighbors on cisco device 
---

- name: Show OSPF neighbors
  hosts: North_Switches
  gather_facts: false
  
  tasks:
  - name: Show status of the OSPF neighbors 
    cisco.ios.ios_command:
      commands:
      - command: "Show ip ospf neighbor"
    register: print_output
  - debug: var=print_output.stdout_lines
