# Ansbible Playbook to add a login banner and new loopback int
---
- name: Add a login banner & a new loopback
  hosts: all

  tasks:
    - name: Adding the Login Banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          trespassers will be shot!
        state: present

    - name: Adding Loopback21
      cisco.ios.ios_interfaces:
        config:
          name: Loopback21
        state: replaced
...
