# Ansbible Playbook to add a login banner and new loopback int
---
- name: Add a login banner & a new loopback
  hosts: all

  tasks:
    - name: Add Banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          trespassers will be shot!
        state: present

    - name: Add loopback
      cisco.ios.ios_interfaces:
        name: Loopback21
        state: present
...
