# Ansbible Playbook to add a login banner using a loop
---
- name: Add a login banner
  hosts: lab_switches
  connection: network_cli

  tasks:
    - name: Adding the Login Banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          Welcome to GH-lab, trespassers will be shot!
        state: present
...
