# Ansible playbook to create a login banner on iosxr device(s)
---
- name: Create a login banner for IOSXR hosts
  hosts: iosxr01
  gather_facts: false
  connection: network_cli

  vars_prompt:
    - name: "username1"
      prompt: "Enter your username" # Prompting user to input username, will be used to login
      private: false

    - name: "password1"
      prompt: Enter you password # Prompting user to input password, will be used to login
      private: true # Note: private set to yes means details will not be displayed on screen

  vars:
    ansible_user: "{{ username1 }}" # Using username input earlier to connect to device(s)
    ansible_password: "{{ password1 }}" # Using password input earlier to authenticate to the device(s)

  tasks:
    - name: Configure the login banner
      cisco.iosxr.iosxr_banner:
        banner: login
        text: |
          @this is a test banner
          that contains a multiline
          string@
        state: present
...
