---
syslog:
  hosts:
    - ip: 140.140.1.5

trunks:
  interfaces:
    - interface: "eth0/1"
      mode: trunk
      native: "50"
      encap: "dot1q"
      allowed: "20,50"
    - interface: "eth0/2"
      mode: trunk
      native: "50"
      encap: "dot1q"
      allowed: "20,50"

access:
  ports:
    - interface: "eth1/0"
      mode: access
      vlan: 20
    - interface: "eth1/1"
      mode: access
      vlan: 20
    - interface: "eth1/2"
      mode: access
      vlan: 666
    - interface: "eth1/3"
      mode: access
      vlan: 666
    - interface: "eth2/0"
      mode: access
      vlan: 666
    - interface: "eth2/1"
      mode: access
      vlan: 666
    - interface: "eth2/2"
      mode: access
      vlan: 666
    - interface: "eth2/3"
      mode: access
      vlan: 666
    - interface: "eth3/0"
      mode: access
      vlan: 666
    - interface: "eth3/1"
      mode: access
      vlan: 666
    - interface: "eth3/2"
      mode: access
      vlan: 666
    - interface: "eth3/3"
      mode: access
      vlan: 666
    - interface: "eth4/0"
      mode: access
      vlan: 666
    - interface: "eth4/1"
      mode: access
      vlan: 666
    - interface: "eth4/2"
      mode: access
      vlan: 666
    - interface: "eth4/3"
      mode: access
      vlan: 666
    - interface: "eth5/0"
      mode: access
      vlan: 666
    - interface: "eth5/1"
      mode: access
      vlan: 666
    - interface: "eth5/2"
      mode: access
      vlan: 666
    - interface: "eth5/3"
      mode: access
      vlan: 666

  vlan:
    - number: 50
      name: "management"
    - number: 10
      name: "Sales"
      svi: "10.100.10.8 255.255.255.0"
#    - number: 20
#      name: "Finance"
#      svi: "10.10.20.8 255.255.255.0"
#    - number: 30
#      name: "HR"
#      svi: "10.100.30.8 255.255.255.0"
    - number: 666
      name: Blackhole

ntp:
  servers:
    - 8.8.8.8
    - 8.8.4.4
...
