---
syslog:
  hosts:
    - ip: 140.140.1.5

vlans:
  vlan:
    - number: 50
      name: "management"
      svi: "10.10.50.6 255.255.255.0"
#    - number: 10
#      name: "Sales"
#      svi: "10.100.10.6 255.255.255.0"
    - number: 20
      name: "SALES"
      svi: "10.10.20.6 255.255.255.0"
    - number: 30
      name: "HR"
      svi: "10.100.30.6 255.255.255.0"
    - number: 40
      name: "VOICE_VLAN"
      svi: "10.100.40.6 255.255.255.0"
    - number: 666
      name: Blackhole
      svi: "66.66.66.6 255.255.255.0"
  interfaces:
    - interface: "eth0/1"
      mode: trunk
      native: "50"
      encap: "dot1q"
      allowed: "10,30,50"
    - interface: "eth0/2"
      mode: trunk
      native: "50"
      encap: "dot1q"
      allowed: "10,30,40,50"
    - interface: "eth1/0"
      mode: access
      vlan: 10
      voice: 40
    - interface: "eth1/1"
      mode: access
      vlan: 30
      voice: 40
    - interface: "eth1/2"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth1/3"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth2/0"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth2/1"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth2/2"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth2/3"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth3/0"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth3/1"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth3/2"
      mode: access
      voice: 40
      vlan: 666
    - interface: "eth3/3"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth4/0"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth4/1"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth4/2"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth4/3"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth5/0"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth5/1"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth5/2"
      mode: access
      vlan: 666
      voice: 40
    - interface: "eth5/3"
      mode: access
      vlan: 666
      voice: 40

ntp:
  servers:
    - 8.8.8.8
    - 8.8.4.4
...
