---
vlans:
  - number: 50
    name: native
  - number: 55
    name: management
  - number: 10
    name: Sales
  - number: 20
    name: Finance
  - number: 30
    name: HR
  - number: 40
    name: voice
  - number: 666
    name: Blackhole

l2_interfaces:
  - { name: eth0/1, mode: trunk, native: 50, encap: dot1q, allowed: 10,20,40,50,55, desc: connected_to_lab-sw3 }
  - { name: eth0/2, mode: trunk, native: 50, encap: dot1q, allowed: 10,20,40,50,55, desc: connected_to_lab-sw4 }
  - { name: eth1/0, mode: access, vlan: 20, voice: 40, desc: access_port }
  - { name: eth1/1, mode: access, vlan: 30, voice: 40, desc: access_port }
  - { name: eth1/2, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth1/3, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth2/0, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth2/1, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth2/2, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth2/3, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth3/0, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth3/1, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth3/2, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth3/3, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth4/0, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth4/1, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth4/2, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth4/3, mode: access, vlan: 666, voice: 40, desc: access_port}
  - { name: eth5/0, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth5/1, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth5/2, mode: access, vlan: 666, voice: 40, desc: access_port }
  - { name: eth5/3, mode: access, vlan: 666, voice: 40, desc: access_port }

l3_interfaces:
  - { name: eth0/0, ip_add: 10.10.10.5, subnet_mask: 255.255.255.0, desc: management_interface }
  - { name: vlan 10, ip_add: 10.100.10.5, subnet_mask: 255.255.255.0, desc: vlan10_svi }
  - { name: lo0, ip_add: 5.5.5.5, subnet_mask: 255.255.255.255, desc: loopback_ospf_id }
  - { name: lo1, ip_add: 99.99.99.99, subnet_mask: 255.255.255.255, desc: loopback1_test }
# - { name: vlan 20, ip_add: 10.100.20.5, subnet_mask: 255.255.255.0, desc: vlan20_svi } }
  - { name: vlan 30, ip_add: 10.100.30.5, subnet_mask: 255.255.255.0, desc: vlan30_svi }
# - { name: vlan 40, ip_add: 10.100.40.5, subnet_mask: 255.255.255.0, desc: vlan40_svi }

static:
  - { ip: 140.140.1.0, mask: 255.255.255.0, int: eth0/0 }

ospf:
  process: 1
  rid: 5.5.5.5
  networks:
    - { network: 10.10.10.0, wildcard: 0.0.0.255, area: 0 }
  default_originate: false

syslog:
  hosts:
    - ip: 140.140.1.10

ntp:
  servers:
    - 8.8.8.8
    - 8.8.4.4
...
