# Ansible Playbook to configure interfaces using cli_config and jinja2
---
- name: "PLAY 1: This playbook configures loopback interfaces using a cli_config module and a jinja"
  hosts: CSR_hosts
  connection: network_cli   # FOR NETWORK DEVICES THE CONNECTION WILL BE 'network_cli'
  tasks:                    # BELOW TASKS IS WHERE EACH TASK IS DEFINED
    - name: "TASK 1: Configure the loopback interfaces that are listed in the host_vars/ directory"
      ansible.netcommon.cli_config:
        config: "{{ lookup('template', '../templates/interface-template.j2') }}"
      notify: config_changed  # a conditional that notifies the handler below if the configuration has changed.
      register: cli_result    # save the output to the 'cli_result'

  handlers:
    - name: "HANDLER OUTPUT: Display output of TASK 1 if configure has changed"
      listen: config_changed  # If the notify sends then config_changed then run debug.msg below
      ansible.builtin.debug:
        msg: "{{ cli_result }}"
...
