# Ansible playbook utilising Ansible_pyats role to take snapshot of routing table
---
- name: Snapshot output test
  hosts: SB-SW-01
  gather_facts: no
  connection: network_cli
  roles:
    - ansible-pyats

  tasks:
    - include_role:
        name: ansible-pyats
        tasks_from: snapshot_command
      vars:
        cisco.ios.ios_command: show ip route
        file: "{{ inventory_hostname }}_routes.json"
...