# Ansible Playbook to test structured data output
---
- name: Structured output test
  hosts: SB-SW-01
  gather_facts: false
  connection: network_cli
  roles:
    - ansible-pyats

  tasks:
    - name: Parse data with pyats
      pyats_parse_command:
          command: show ip route
      register: output

    - name: Print output to screen
      ansible.builtin.debug:
        var: output
...
