---

- name: "Playbook to Validate device facts against host data files"
  hosts: Canada, vEOS
  connection: network_cli

  tasks:
    - name: "Task1 - use NAPALM Validate"
      napalm_validate:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        validation_file: "{{ inventory_hostname }}-facts.yml"
      register: result
      ignore_errors: yes
#using napalm validate to validate a set of facts about hosts
    - name: "Task1 - print the result"
      debug:
        msg: "{{ result }}"
...
