#Ansible playbook to add basic SNMP server configuraiton to cisco IOS devices

---
- name: Add basic SNMP Server config
  hosts: all
  gather_facts: false
  connection: local
  
  vars:
    cli:
      username: geordie
      password: teabag22

  tasks:
    - name: add basic SNMP configuration
      ios_config:
        lines:
          - service tcp-keepalives-in
          - service tcp-keepalives-out
          - snmp-server community labro
          - snmp-server enable traps
          - snmp-server host 80.80.80.1 version 2c labro
          - do wr mem
          
      register: print_output
    -  debug: var=print_output
...
