# Ansible Playbook to copy running configs to a file
---
- name: Backup running config to file
  hosts: routers

  vars:
    cli:
      username: cisco
      password: cisco123

  tasks:
    - name: Run backups
      cisco.ios.ios_command:
        commands:
          - show run
        host: "{{ ansible_host }}"
      register: config

    - name: Save output to backups
      ansible.builtin.copy:
        content: "{{ config.stdout[0] }}"
        dest: "/etc/ansible/backups/show_run_{{ inventory_hostname }}.txt"
        mode: '644'
...
