# Ansible Playbook to show routes learnt via ospf on cisco device 
---

- name: Show OSPF learnt routes
  hosts: Opus, Selby
  gather_facts: false
  connection: network_cli
  
  tasks:
  - name: Show OSPF routes in the routing table 
    cisco.ios.ios_command:
      commands:
      - command: "Show ip route ospf"
    register: print_output
  - debug: var=print_output.stdout_lines
