# Ansible Playbook to show routes learnt via ospf on cisco device 
---

- name: Show OSPF learnt routes
  hosts: Core1
  gather_facts: false
  
  tasks:
  - name: Show OSPF routes in the routing table 
    cisco.ios.ios_command:
      commands:
      - command: "Show ip route ospf"
    register: print_output
  - debug: var=print_output.stdout_lines
