# Ansible Playbook to show trunk interface information on cisco switch(es) 
---

- name: Show trunk interfaces
  hosts: SB-SW-01
  gather_facts: false
  connection: network_cli
  
  tasks:
  - name: Show the trunk interfaces on the switch 
    cisco.ios.ios_command:
      commands:
      - command: "Show interface trunk"
    register: print_output
  - debug: var=print_output.stdout_lines
