# Ansible playbook to show ip route on cisco ios devices and print the output to screen

---

- name: Get IP routes
  hosts: North-Switches
  gather_facts: false
  
  tasks:
    - name: show IP route on devices
      raw: "show IP route"
      register: print_output
    - debug: var=print_output.stdout_lines
...
