---

BGP:
  ASN: "65001"
  peers:
    - neighbor: "22.22.22.2"
      peer_asn: "65002"

    - neighbor: "23.23.23.2"
      peer_asn: "65003"
  
    - neighbor: "24.24.24.2"
      peer_asn: "65004"

  redistribute: "connected"

eigrp_style: "named"

eigrp:
  asn: "1"
  rid: "1.1.1.1"
  networks: 
    - "1.1.1.1 0.0.0.0"
    - "12.12.12.0 0.0.0.255"
    - "22.22.22.0 0.0.0.255"

ospf:
  rid: 1.1.1.1
  
ntp:
  servers:
    - 8.8.8.8
    - 8.8.4.4
    - 99.99.99.99