---
- name: "configure BGP from Jinja template"
  hosts: "routers"
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Configuring BGP"
      cisco.ios.ios_config:
        src: "BGP.j2"
        save_when: modified
      notify: bgp_handler
      register: bgp_result

  handlers:
    - name: "bgp_handler - This will check if BGP config has been changed"
      listen: bgp_handler
      debug:
        msg: "CONFIG THAT HAS BEEN ADDED: {{ bgp_result.commands }}"
...
