---
#Playbook using jinja2 templates to configure VLAN on Cisco Switches
- name: "VLAN Playbook using Jinja2 Templates"
  hosts: Canada
  connection: network_cli

  tasks:
    - name: "Configure Cisco VLAN"
      cisco.ios.ios_config:
        src: "{{ ansible_network_os }}-vlans.j2"
      register: cisco_vlan_output
      when: "ansible_network_os == 'cisco.ios.ios'"


    - name: "Print Cisco vlan config"
      debug:
        msg: "{{ cisco_vlan_output }}"
      when: "ansible_network_os == 'cisco.ios.ios'"
...
