# Ansible playbook to Enable CDP
---
- name: Enabling CDP to devices
  hosts: North_Switches, South_Switches
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Configuring CDP
      cisco.ios.ios_config:
        commands:
          - "cdp run"
        save_when: changed

    - name: Validate CDP is enabled
      cisco.ios.ios_command:
        commands:
          - "show cdp neigh"
      register: print_output

    - name: Output cdp neigh output to screen
      ansible.builtin.debug:
        var: print_output.stdout_lines
...
