# Playbook to configure Syslog traps and server on Cisco devices
# hostname = IP address of the log servers
---
- name: Configure Syslog traps on cisco devices
  hosts: NN-SW-01
  connection: network_cli

  tasks:
    - name: Push the Logging configuration to the devices
      cisco.ios.ios_logging_global:
        config:
          hosts:
            - hostname: 172.16.1.12
            - hostname: 172.16.1.11
          buffered:
            severity: notifications
            size: 5099
            xml: true
          console:
            severity: critical
            xml: true
          facility: local5
          transport:
            tcp:
              port: 514
          monitor:
            severity: warnings
          message_counter: log
          snmp_trap:
            - errors
          trap: errors
          userinfo: true
        state: merged
...
