# Ansible Playbook to add new vlans, create trunks and create the L2 interfaces and add the VLANs
---
- name: Configure new VLANs on each IOS Switch
  hosts: North_Switches, South_Switches
  gather_facts: false
  connection: local

  tasks:
    - name: Create new VLANs and merge with existing VLANs on the device
      cisco.ios.ios_vlans:
        config:
          - name: HR_VLAN
            vlan_id: 10
            state: active
            shutdown: disabled
          - name: Finance_VLAN
            vlan_id: 20
            state: active
            shutdown: disabled
          - name: VOICE_VLAN
            vlan_id: 30
            state: active
            shutdown: disabled
          - name: Management_VLAN
            vlan_id: 50
            state: active
            shutdown: disabled
          - name: Blackhole_VLAN
            vlan_id: 666
            state: active
            shutdown: enabled
        state: merged

    - name: Show merged VLAN information
      cisco.ios.ios_command:
        commands:
          - show vlan brief
      register: print_vlan

    - name: Print the vlan output to screen
      ansible.builtin.debug:
        var: print_vlan.stdout_lines

    - name: Save the new runnig configuration to memory
      cisco.ios.ios_command:
        commands: wr mem
...
