# Playbook to add an ACL to Cisco Switch
---
- name: Add ACL to cisco device
  hosts: SW01

  gather_facts: false
  connection: network_cli

  tasks:
    - name: Configure ACL on Cisco Switch
      cisco.ios.ios_config:
        lines:
          - access-list 99 permit 172.16.1.100

    - name: Verify ACL is present
      cisco.ios.ios_command:
        commands:
          - sh access-l
        waitfor:
          - result[0] contains 'permit 172.16.1.100'

    - name: Save the config
      cisco.ios.ios_config:
        save_when: modified
...
