# Ansible playbook to Enable LLDP
---
- name: Playbook to enable lldp on hosts
  hosts: CSR_hosts
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Configuring LLDP on hosts
      cisco.ios.ios_config:
        commands:
          - "lldp run"
        save_when: changed

    - name: Validate LLDP is enabled
      cisco.ios.ios_command:
        commands:
          - "show lldp neighbors"
      register: print_output

    - name: Output lldp neigh output to screen
      ansible.builtin.debug:
        var: print_output.stdout_lines
...
