# Ansible playbook using Jinja2 templates to configure VLAN, L2 and L3 interfaces
---
- name: "Play 1 Update l3 interface configuration"
  hosts: lab-sw5
  connection: network_cli

  tasks:
    - name: "Task1: Deploy the l3 interface configuration"
      cisco.ios.ios_config:
        src: "templates/ios_l3_interfaces.j2"
      register: ios_config_output
      ignore_errors: true

    - name: "Task2: Deploy the VLANs and L2 interface configuration"
      cisco.ios.ios_config:
        src: "templates/ios_l2_interfaces.j2"
      register: ios_config_output
      ignore_errors: true
      timeout: 180

    - name: "Task3: Save the configuration changes"
      cisco.ios.ios_command:
        commands: 
          - wr mem

    - name: "Task4: Display the configuration changes"
      ansible.builtin.debug:
        msg: "{{ ios_config_output }}"
...
