# Ansible playbook using Jinja2 template to configure OSPF on IOS switches
---
- name: "Play 1 Add OSPF to Hosts via jinj2 template"
  hosts: lab_switches
  connection: network_cli

  tasks:
    - name: "Task1: Deploy OSPF configuration"
    cisco.ios.ios_config:
      src: "templates/ospf.j2"
    register: ios_ospf_output
    ignore_errors: true

  - name: "Task2: Save the configuration changes"
    cisco.ios.ios_command:
      commands:
        - wr mem

  - name: "Task3: Display the configuration changes"
    ansible.builtin.debug:
      msg: "{{ ios_ospf_output }}"
...
