#Ansible playbook to set DNS nameservers on cisco IOS devices

---
- hosts: SB-SW-01
  gather_facts: no
  connection: network_cli
  
  vars:                
    dns_servers:
    - ip name-server 8.8.8.8
    - ip name-server 8.8.4.4
      
  tasks:
  
  - name: get the current name-server configs
    ios_command:
      commands:
        - "show running-config full | include ip name-server"
    register: get_config
    when: 

  - debug: var=get_config.stdout_lines

  - name: set name-server commands
    with_items: "{{ dns_servers }}"
    ios_config:
      lines:
        - "{{ item }}"
    register: set_dns

...