# Playbook using Ansible VLANs module to configure VLAN on Cisco Switches
---
- name: Configure vlan on Cisco Switch
  hosts: Canada
  connection: network_cli

  tasks:
    - name: Push Cisco vlan Config
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.interface }}"
            mode: access
            access:
              vlan: "{{ item.vlan }}"
        state: merged
      register: cisco_output
      loop: "{{ vlans.interfaces }}"
      when: item.mode == "access"

    - name: Print the configuration to screen
      ansible.builtin.debug:
        msg: "{{ cisco_output }}"
...
