# Ansible playbook to test ip reachablity over a specified VRF
---
- name: Test IP reachability over specific VRF
  hosts: R1
  gather_facts: false
  connection: network_cli
  vars_prompt:
    - name: "username1"
      prompt: "Enter your username" # Prompting user to input username, will be used to login
      private: false
    - name: "password1"
      prompt: Enter you password # Prompting user to input password, will be used to login
      private: true # Note: private set to yes means details will not be displayed on screen

    - name: "VRF"
      prompt: "Enter the VRF name" # Promting user to add the VRF name, will be used later in the playbook
      private: false # Note: private set to no means details will be displayed on screen
    - name: "IP"
      prompt: Enter destination IP address to test # Prompting user to input the ip address, will be used later in the playbook
      private: false

  vars:
    ansible_user: "{{ username1 }}" # Using username input earlier to connect to device(s)
    ansible_password: "{{ password1 }}" # Using password input earlier to authenticate to the device(s)

  tasks:
  - name: Test reachability to 198.51.100.252 using prod vrf
    cisco.ios.ios_ping:
      dest: "{{ IP}}" # Using the ip address input by user for ping test
      vrf: " {{ VRF }}" # Using vrf name input by user to test if the IP address is reachable over the VRF
      afi: ip
      count: 10
    register: ip_test

  - name: Print IP test output to screen
    ansible.builtin.debug:
      var: ip_test.stdout_lines  # Telling ansible to use ip_test results and output and display on screen
...
