# Ansible playbook useing Jinja2 templates to send OSPF information held in the template to each device
---
- name: First Play - Automate Routing Configs via Jinja2
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: First Task - Identify Correct Jinja Template
      ansible.builtin.set_fact:
        ospf_path: templates/{{ ospf_os_type }}_ospf.j2

    - name: Second Task - Source Template & Apply Configs!
      ansible.netcommon.cli_config:
        config: "{{ lookup('template', ospf_path) }}"
      notify: config_changed
      register: response

  handlers:
    - name: Output Changes...
      listen: config_changed
      ansible.builtin.debug:
        msg: "{{ response }}"
