# Ansible Playbook to show vlan information on cisco switch(es) 
---

- name: Show VLAN details
  hosts: Opus
  gather_facts: false
  connection: network_cli
  
  tasks:
  - name: Show brief summary of VLANs on the device(s) 
    cisco.ios.ios_command:
      commands:
      - command: "Show vlan brief"
    register: print_output
  - debug: var=print_output.stdout_lines
