---

syslog:
  hosts:
    - ip: 140.140.1.5
    
bgp:
  asn: "2"
  rid: "2.2.2.2"
  neighbors:
    - neighbor: "22.22.22.1"
      peer_asn: "1"
    - neighbor: "223.23.23.2"
      peer_asn: "3" 
  networks:
    - network: "12.2.2.2"
      mask: "255.255.255.255"

#BGP:
#  ASN: "65002"
#  peers:
#    - neighbor: "22.22.22.1"
#      peer_asn: "65001"
#    - neighbor: "23.23.23.2"
#      peer_asn: "65003"
#    - neighbor: "24.24.24.2"
#      peer_asn: "65004"
#  redistribute: "connected"
#  update_source: "loo0"

ospf:
  default_originate: false
  process: 1
  rid: "2.2.2.2"
  networks:
    - network: "12.12.12.0"
      wildcard: "0.0.0.255"
      area: 0
    - network: "22.22.22.0"
      wildcard: "0.0.0.255"
      area: 0    

eigrp_style: "normal"

eigrp:
  asn: "2"